---
# https://taskfile.dev

version: '3'

env:
  DOCKER_IMAGE: python.ie/website-dev
  PGDATABASE: pythonie
  PGPASSWORD: pythonie
  PGUSER: postgres
  PGHOST: 127.0.0.1
  HEROKU_APP: pythonie

dotenv: ['production.env']

tasks:
  database:drop:
    desc: Drop the local PostgreSQL database
    cmds:
      - docker compose exec -u postgres postgres dropdb --if-exists $PGDATABASE

  database:pull:
    desc: Pull the database from Heroku and store it into a localhost PostgreSQL
    cmds:
      - heroku pg:pull $HEROKU_POSTGRESQL_IDENTIFIER $PGDATABASE

  database:push:
    desc: Push the database from local PostgreSQL to Heroku
    cmds:
      - heroku pg:push $PGDATABASE $HEROKU_POSTGRESQL_IDENTIFIER

  database:reset:
    desc: Reset the database with a fresh copy of the official database
    cmds:
      - task: database:drop
      - task: database:pull

  heroku:database:backups:
    desc: Show the backups of the database
    cmds:
      - heroku pg:backups

  heroku:database:run-backup:
    desc: Run a remote backup
    cmds:
      - heroku pg:backups:capture

  heroku:logs:
    desc: View application logs in real-time
    cmds:
      - heroku logs --tail

  heroku:restart:
    desc: Restart the Heroku application
    cmds:
      - heroku restart

  heroku:shell:
    desc: Run Django shell on Heroku
    cmds:
      - heroku run python pythonie/manage.py shell --settings=pythonie.settings.production

  heroku:bash:
    desc: Run bash shell on Heroku
    cmds:
      - heroku run bash

  heroku:migrate:
    desc: Run database migrations on Heroku
    cmds:
      - heroku run python pythonie/manage.py migrate --settings=pythonie.settings.production

  heroku:config:
    desc: Show Heroku environment variables
    cmds:
      - heroku config

  heroku:ps:
    desc: Show dyno status
    cmds:
      - heroku ps

  heroku:releases:
    desc: Show deployment history
    cmds:
      - heroku releases

  heroku:rollback:
    desc: Rollback to previous release
    cmds:
      - heroku rollback

  heroku:maintenance:on:
    desc: Enable maintenance mode
    cmds:
      - heroku maintenance:on

  heroku:maintenance:off:
    desc: Disable maintenance mode
    cmds:
      - heroku maintenance:off

  run:postgres:
    desc: Only run the PostgreSQL server, for example, if you want to restore the database from Heroku
    cmds:
      - docker compose run --remove-orphans --detach --service-ports postgres

  run:
    desc: Run a local version of PythonIE
    cmds:
      - docker compose run --remove-orphans --rm --service-ports web python pythonie/manage.py runserver 0.0.0.0:8000

  django:shell-plus:
    desc: Run Django shell_plus
    cmds:
      - docker compose run --rm web python pythonie/manage.py shell_plus

  shell:
    desc: Run a shell
    cmds:
      - docker compose run --rm web /bin/bash

  django:make-migrations:
    desc: Make migrations
    cmds:
      - docker compose run --rm web python pythonie/manage.py makemigrations

  django:migrate:
    desc: Run database migrations
    cmds:
      - docker compose run --rm web python pythonie/manage.py migrate

  django:collect-static:
    desc: Collect static files
    cmds:
      - docker compose run --rm web python pythonie/manage.py collectstatic

  dependencies:compute:
    desc: Compute the dependencies
    cmds:
      - toast deps:compute

  dependencies:outdated:
    desc: List the outdated dependencies
    cmds:
      - toast deps:outdated

  dependencies:upgrade:
    desc: Upgrade the dependencies
    cmds:
      - toast deps:upgrade

  dependencies:upgrade:django:
    desc: Upgrade Django to the latest compatible version
    cmds:
      - toast deps:upgrade:django

  dependencies:upgrade:wagtail:
    desc: Upgrade Wagtail to the latest compatible version
    cmds:
      - toast deps:upgrade:wagtail

  dependencies:security:
    desc: Check dependencies for known security vulnerabilities
    cmds:
      - toast deps:security

  dependencies:tree:
    desc: Show the dependencies tree
    cmds:
      - toast deps:tree

  docker:build:
    desc: Build the docker image
    cmds:
      - docker build --no-cache -t $DOCKER_IMAGE .

  docker:run:
    desc: Run a shell into the docker container
    cmds:
      - docker compose run web /bin/bash

  stack:pull:
    desc: Pull the docker images for the stack
    cmds:
      - docker compose pull postgres minio mc redis

  stack:services:
    desc: List the services from the docker compose file
    cmds:
      - docker compose config --services

  pycon:import:sessionize:
    desc: Import the information from Sessionize
    cmds:
      - docker compose run web python pythonie/manage.py import-sessionize --file sessionize.xlsx

  pycon:import:sessionize:json:
    desc: Import the information from Sessionize
    cmds:
      - docker compose run web python pythonie/manage.py update-sessionize-json-stream

  code:format:
    desc: Format the code
    cmds:
      - toast code:format

  code:lint:
    desc: Lint the code and fix issues
    cmds:
      - toast code:lint

  code:check:
    desc: Check code formatting and linting without changes
    cmds:
      - toast code:check

  dependencies:upgrade:package:
    desc: "Upgrade a specific package (usage: task dependencies:upgrade:package PACKAGE=django)"
    cmds:
      - python -m uv pip compile --upgrade-package $PACKAGE --output-file requirements/main.txt requirements/main.in
      - python -m uv pip compile --upgrade-package $PACKAGE --output-file requirements/dev.txt requirements/dev.in
      - python -m uv pip compile --upgrade-package $PACKAGE --output-file requirements/production.txt requirements/production.in

  tests:
    desc: Run all tests
    cmds:
      - docker compose run --rm -e DJANGO_SETTINGS_MODULE=pythonie.settings.tests web python pythonie/manage.py test pythonie --verbosity=3

  down:
    desc: Stop the docker compose stack
    cmds:
      - docker compose down
