# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_delete_meetupupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='sponsors',
            field=models.ManyToManyField(blank=True, through='meetups.MeetupSponsorRelationship', to='sponsors.Sponsor'),
        ),
    ]
