# Generated by Django 3.2.15 on 2022-09-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0006_auto_20160703_0857"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meetup",
            options={"ordering": ["-time"]},
        ),
    ]
