# Generated by Django 3.2.15 on 2022-09-29 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0066_collection_management_permissions"),
        ("speakers", "0002_talkspage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                ("picture_url", models.CharField(blank=True, max_length=255)),
                ("biography", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
            bases=("wagtailcore.page",),
        ),
        migrations.RemoveField(
            model_name="speakerspage",
            name="api_url",
        ),
        migrations.RemoveField(
            model_name="talkspage",
            name="api_url",
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField()),
                ("scheduled_at", models.DateTimeField()),
                ("duration", models.IntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("talk", "Talk"), ("workshop", "Workshop")],
                        db_index=True,
                        default="talk",
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("accepted", "Accepted"),
                            ("confirmed", "Confirmed"),
                            ("refused", "Refused"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="speakers.room"
                    ),
                ),
                (
                    "speakers",
                    models.ManyToManyField(
                        related_name="sessions", to="speakers.Speaker"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            bases=("wagtailcore.page",),
        ),
    ]
