# Generated by Django 3.2.15 on 2022-09-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0003_auto_20220929_1828"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
