# Generated by Django 5.0.14 on 2025-11-21 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("speakers", "0003_auto_20220929_1828"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="speakers.room"
            ),
        ),
    ]
