# Generated by Django 3.2.15 on 2022-09-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0004_alter_speaker_external_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="talkspage",
            name="api_url",
        ),
        migrations.AlterField(
            model_name="session",
            name="speakers",
            field=models.ManyToManyField(
                related_name="sessions", to="speakers.Speaker"
            ),
        ),
    ]
