# Generated by Django 3.2.15 on 2022-10-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0005_auto_20220930_0728"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="picture_url",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
